### PR TITLE
Covid updates command

### PR DESCRIPTION
**Pull request by FarshanAhamed**
feature #1 - Added command to get COVID updates using a public API

command - "covid"
alias - "covid status", "covid stats", "covid news", "covid today", "covid updates", "corona", "coronavirus"

The working of the command

image

### CODE REVIEW

**Comment by MattTheDev** [comment]
Hey @FarshanAhamed - Thanks so much for this. Over the next couple weeks, as I get more, I'll add this to the bot!  Hopefully we can eventually turn it off! :( But until then - it'll be good to have!

**Comment by MattTheDev** [comment]
@all-contributors please add @FarshanAhamed  for the COVID Information Command.

**Comment by MattTheDev** [comment]
@all-contributors please add @FarshanAhamed for code

**Comment by FarshanAhamed** [comment]
Thank you @MattTheDev

**Pull request merged**
